# Generated by Django 5.2.9 on 2025-12-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=100)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_log",
                "managed": True,
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="audit_created_idx"),
                    models.Index(fields=["user_id", "-created_at"], name="audit_user_created_idx"),
                    models.Index(fields=["action"], name="audit_action_idx"),
                ],
            },
        ),
    ]
